name: CI Oracle 21

on:
  push:
    branches:
      - main
    paths:
      - oracle/**
      - .github/workflows/ci_oracle.yaml
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: oracle

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    services:
      oracle-21c:
        image: container-registry.oracle.com/database/express:21.3.0-xe
        ports:
          - 1531:1521
        options: >-
          --env ORACLE_PWD=test
          --env ORACLE_CHARACTERSET=AL32UTF8
          --health-cmd="echo 'SELECT 1 FROM dual;' | sqlplus -s system/test@localhost:1521/XE"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          version: '2.1.0'
      - name: Install
        run: poetry install
      - name: lint
        run: make lint
        run: PORT=1531 poetry run pytest tests
